name: 'Release Packages'
description: 'Release All packages To Set Registry'

inputs:
  dry-run:
    required: false
    description: 'Dry run release'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x 

    # Clean deno Install
    - name: Deno install
      run: deno install
      shell: bash

    # Bundle packages.
    - name: Build
      run: deno task kg bundle --all
      shell: bash

    # Release Public Packages
    - name: Release
      if: ${{ inputs.dry-run == 'false' }}
      run: deno publish
      shell: bash
      
    # Release Public Packages on dry run
    - name: Release dry run
      if: ${{ inputs.dry-run == 'true' }}
      run: deno publish --dry-run
      shell: bash