export enum BufferPrimitiveFormat {
    Unsupported = 'Unsupported primitive format',
    Float = 'float',
    Vec2Float = 'vector-2-float',
    Vec3Float = 'vector-3-float',
    Vec4Float = 'vector-4-float',
    Uint = 'unsigned-integer',
    Vec2Uint = 'vector-2-unsigned-integer',
    Vec3Uint = 'vector-3-unsigned-integer',
    Vec4Uint = 'vector-4-unsigned-integer',
    Int = 'integer',
    Vec2Int = 'vector-2-integer',
    Vec3Int = 'vector-3-integer',
    Vec4Int = 'vector-4-integer',
}