export enum PgslBuildInTypeName {
    VertexIndex = 'VertexIndex',
    InstanceIndex = 'InstanceIndex',
    Position = 'Position',
    FrontFacing = 'FrontFacing',
    FragDepth = 'FragDepth',
    SampleIndex = 'SampleIndex',
    SampleMask = 'SampleMask',
    LocalInvocationId = 'LocalInvocationId',
    LocalInvocationIndex = 'LocalInvocationIndex',
    GlobalInvocationId = 'GlobalInvocationId',
    WorkgroupId = 'WorkgroupId',
    NumWorkgroups = 'NumWorkgroups',
    ClipDistances = 'ClipDistances',
}