/**
 * Gpu limit names.
 */
export enum GpuLimit {
    MaxTextureDimension1D = 'maxTextureDimension1D',
    MaxTextureDimension2D = 'maxTextureDimension2D',
    MaxTextureDimension3D = 'maxTextureDimension3D',
    MaxTextureArrayLayers = 'maxTextureArrayLayers',
    MaxBindGroups = 'maxBindGroups',
    MaxBindGroupsPlusVertexBuffers = 'maxBindGroupsPlusVertexBuffers',
    MaxBindingsPerBindGroup = 'maxBindingsPerBindGroup',
    MaxDynamicUniformBuffersPerPipelineLayout = 'maxDynamicUniformBuffersPerPipelineLayout',
    MaxDynamicStorageBuffersPerPipelineLayout = 'maxDynamicStorageBuffersPerPipelineLayout',
    MaxSampledTexturesPerShaderStage = 'maxSampledTexturesPerShaderStage',
    MaxSamplersPerShaderStage = 'maxSamplersPerShaderStage',
    MaxStorageBuffersPerShaderStage = 'maxStorageBuffersPerShaderStage',
    MaxStorageTexturesPerShaderStage = 'maxStorageTexturesPerShaderStage',
    MaxUniformBuffersPerShaderStage = 'maxUniformBuffersPerShaderStage',
    MaxUniformBufferBindingSize = 'maxUniformBufferBindingSize',
    MaxStorageBufferBindingSize = 'maxStorageBufferBindingSize',
    MinUniformBufferOffsetAlignment = 'minUniformBufferOffsetAlignment',
    MinStorageBufferOffsetAlignment = 'minStorageBufferOffsetAlignment',
    MaxVertexBuffers = 'maxVertexBuffers',
    MaxBufferSize = 'maxBufferSize',
    MaxVertexAttributes = 'maxVertexAttributes',
    MaxVertexBufferArrayStride = 'maxVertexBufferArrayStride',
    MaxInterStageShaderVariables = 'maxInterStageShaderVariables',
    MaxColorAttachments = 'maxColorAttachments',
    MaxColorAttachmentBytesPerSample = 'maxColorAttachmentBytesPerSample',
    MaxComputeWorkgroupStorageSize = 'maxComputeWorkgroupStorageSize',
    MaxComputeInvocationsPerWorkgroup = 'maxComputeInvocationsPerWorkgroup',
    MaxComputeWorkgroupSizeX = 'maxComputeWorkgroupSizeX',
    MaxComputeWorkgroupSizeY = 'maxComputeWorkgroupSizeY',
    MaxComputeWorkgroupSizeZ = 'maxComputeWorkgroupSizeZ',
    MaxComputeWorkgroupsPerDimension = 'maxComputeWorkgroupsPerDimension',
}
