export const PgslOperator = {
    None: '',
    Plus: '+',
    Minus: '-',
    Multiply: '*',
    Divide: '/',
    Modulo: '%',
    Not: '!',
    ShiftLeft: '<<',
    ShiftRight: '>>',
    GreaterThan: '>',
    LowerThan: '<',
    GreaterThanEqual: '>=',
    LowerThanEqual: '<=',
    Equal: '==',
    BinaryAnd: '&',
    BinaryOr: '|',
    BinaryXor: '^',
    BinaryNegate: '~',
    ShortCircuitAnd: '&&',
    ShortCircuitOr: '||',
    NotEqual: '!=',
    Increment: '++',
    Decrement: '--',
} as const;
export type PgslOperator = typeof PgslOperator[keyof typeof PgslOperator];