name: 'Bump package versions'

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type to update. [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]'
        required: true
      prerelease-id:
        description: 'Prerelease ID'
        required: false
        default: ''

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  test:
    if: ${{ !contains(github.event.head_commit.message, '[Version-Bump]') }}
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/npm-test

  bump-version:
    if: ${{ !contains(github.event.head_commit.message, '[Version-Bump]') }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout needed for local composite file.
      - uses: actions/checkout@v3
      # Run local composite bump version.
      - name: 'Bump Version'
        uses: ./.github/actions/bump-version
        with:
          version-type: ${{ inputs.version-type }}
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          prerelease-id: ${{ inputs.prerelease-id }}

  empty-job:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Catch no job
        run: echo "Catch no job"

 
      
