name: NPM Package Release

on:
  release:
    types: [published]

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: NPM Install
        run: npm ci --ignore-scripts

      - name: Tests
        run: npm run test -- --force

  publish-npm-packages:
    needs: test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:  
          token: ${{ secrets.CI_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@kartoffelgames'

      - name: NPM install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build -- --force

      - name: Release
        run: npm publish -ws --access public

      
