name: 'Test All Packages'

on:
  push:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Run local composite test.
      - name: 'Test Packages'
        uses: ./.github/actions/run-tests

      # Dry run publish.
      - name: 'Test JSR Publish'
        uses: ./.github/actions/release-jsr-packages
        with:
          dry-run: true

      # Dry run publish.
      - name: 'Test NPM Publish'
        uses: ./.github/actions/release-npm-packages
        with:
          registry-token: ${{ secrets.CI_NPM_TOKEN }}
          registry-url: 'https://registry.npmjs.org'
          registry-scope: '@kartoffelgames'
          dry-run: true
      