name: Test All Packages

on:
  pull_request:
    branches:
      - 'development'
      - 'master'

jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm run workflow:update-version-numbers
      - run: npm ci --ignore-scripts
      - run: npx turbo run test --force



      
